trigger:
  - main  # Or the branch you want to trigger the build on

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  docfxVersion: '2.76.0'  # Specify DocFX version

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Replace with the specific version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- powershell: |
    Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/archive/refs/tags/v$(docfxVersion).zip" -OutFile "docfx-$(docfxVersion).zip"
    Expand-Archive -Path "docfx-$(docfxVersion).zip" -DestinationPath "$(Agent.ToolsDirectory)/docfx"
    $env:PATH += ";$(Agent.ToolsDirectory)/docfx"
  displayName: 'Download and Install DocFX'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    dotnet tool update -g docfx
    docfx $(Agent.ToolsDirectory)/docfx.json
  displayName: 'Build DocFX Documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docs/_site'
    ArtifactName: 'docs'
  displayName: 'Publish Documentation'
