trigger:
  - main  # Or the branch you want to trigger the build on

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  docfxVersion: 'v2.7.26'  # Specify DocFX version

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Replace with the specific version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- powershell: |
    $docfxUrl = "https://github.com/dotnet/docfx/archive/refs/tags/v$(docfxVersion).zip"
    $docfxZipPath = "$(Build.SourcesDirectory)\docfx-$(docfxVersion).zip"
    $docfxExtractPath = "$(Build.SourcesDirectory)\docfx"
    
    Invoke-WebRequest -Uri $docfxUrl -OutFile $docfxZipPath
    Expand-Archive -Path $docfxZipPath -DestinationPath $docfxExtractPath

    $docfxPath = Join-Path -Path $docfxExtractPath -ChildPath "docfx"
    $env:PATH += ";$docfxPath"
    
    Write-Output "DocFX downloaded and extracted to $docfxPath"
  displayName: 'Download and Install DocFX'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    $(Build.SourcesDirectory)\docfx\docfx.exe build --config docfx.json
  displayName: 'Build DocFX Documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docs/_site'
    ArtifactName: 'docs'
  displayName: 'Publish Documentation'
