trigger:
  - main  # Or the branch you want to trigger the build on

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  docfxVersion: '2.76.0'  # Specify DocFX version if needed

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Replace with the specific version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    curl -L -o docfx.zip https://github.com/dotnet/docfx/archive/refs/tags/v(docfxVersion).zip
    tar -xf docfx.zip -C $(Agent.ToolsDirectory)
    set PATH=$(Agent.ToolsDirectory)/docfx:%PATH%
  displayName: 'Install DocFX'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    $(Agent.ToolsDirectory)/docfx/docfx.exe build --config docfx.json
  displayName: 'Build DocFX Documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docs/_site'
    ArtifactName: 'docs'
  displayName: 'Publish Documentation'
