trigger:
  - main  # Or the branch you want to trigger the build on

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  docfxVersion: 'latest'  # Specify DocFX version if needed

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    sudo apt-get update
    sudo apt-get install -y mono-complete
    sudo apt-get install -y docfx
  displayName: 'Install Mono and DocFX'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    docfx build
  displayName: 'Build DocFX Documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docs/_site'
    ArtifactName: 'docs'
  displayName: 'Publish Documentation'