trigger:
  - main  # Or the branch you want to trigger the build on

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  docfxVersion: '2.59.4'  # Specify DocFX version if needed

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Replace with the specific version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    choco install docfx --version=$(docfxVersion) -y
  displayName: 'Install DocFX'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    docfx build
  displayName: 'Build DocFX Documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docs/_site'
    ArtifactName: 'docs'
  displayName: 'Publish Documentation'
