trigger:
  - main  # Or the branch you want to trigger the build on

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  docfxVersion: 'v2.59.2'  # Specify DocFX version if needed

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Replace with the specific version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- powershell: |
    $docfxUrl = "https://github.com/dotnet/docfx/releases/download/$(docfxVersion)/docfx.zip"
    $docfxZipPath = "$(Build.SourcesDirectory)\docfx.zip"
    $docfxExtractPath = "$(Build.SourcesDirectory)\docfx"

    Invoke-WebRequest -Uri $docfxUrl -OutFile $docfxZipPath
    Expand-Archive -Path $docfxZipPath -DestinationPath $docfxExtractPath
  displayName: 'Download and Extract DocFX'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    $(Build.SourcesDirectory)\docfx\docfx.exe build docfx.json
  displayName: 'Build DocFX Documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docs/_site'
    ArtifactName: 'docs'
  displayName: 'Publish Documentation'
