### YamlMime:ManagedReference
items:
- uid: Iktan.Ecommerce.App.Interface.IUserApplication
  commentId: T:Iktan.Ecommerce.App.Interface.IUserApplication
  id: IUserApplication
  parent: Iktan.Ecommerce.App.Interface
  children:
  - Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IUserApplication
  nameWithType: IUserApplication
  fullName: Iktan.Ecommerce.App.Interface.IUserApplication
  type: Interface
  source:
    remote:
      path: Iktan.Ecommerce.App.Interface/IUserApplication.cs
      branch: dev
      repo: https://github.com/ReinelPuentes92/ArquitectDDD.git
    id: IUserApplication
    path: Iktan.Ecommerce.App.Interface/IUserApplication.cs
    startLine: 5
  assemblies:
  - Iktan.Ecommerce.App.Interface
  namespace: Iktan.Ecommerce.App.Interface
  syntax:
    content: public interface IUserApplication
    content.vb: Public Interface IUserApplication
- uid: Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate(System.String,System.String)
  commentId: M:Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate(System.String,System.String)
  id: Authenticate(System.String,System.String)
  parent: Iktan.Ecommerce.App.Interface.IUserApplication
  langs:
  - csharp
  - vb
  name: Authenticate(string, string)
  nameWithType: IUserApplication.Authenticate(string, string)
  fullName: Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate(string, string)
  type: Method
  source:
    remote:
      path: Iktan.Ecommerce.App.Interface/IUserApplication.cs
      branch: dev
      repo: https://github.com/ReinelPuentes92/ArquitectDDD.git
    id: Authenticate
    path: Iktan.Ecommerce.App.Interface/IUserApplication.cs
    startLine: 7
  assemblies:
  - Iktan.Ecommerce.App.Interface
  namespace: Iktan.Ecommerce.App.Interface
  syntax:
    content: Task<Response<UserDTO>> Authenticate(string userName, string password)
    parameters:
    - id: userName
      type: System.String
    - id: password
      type: System.String
    return:
      type: System.Threading.Tasks.Task{Iktan.Ecommerce.Transversal.Common.Response{Iktan.Ecommerce.App.DTO.UserDTO}}
    content.vb: Function Authenticate(userName As String, password As String) As Task(Of Response(Of UserDTO))
  overload: Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate*
  nameWithType.vb: IUserApplication.Authenticate(String, String)
  fullName.vb: Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate(String, String)
  name.vb: Authenticate(String, String)
references:
- uid: Iktan.Ecommerce.App.Interface
  commentId: N:Iktan.Ecommerce.App.Interface
  href: Iktan.html
  name: Iktan.Ecommerce.App.Interface
  nameWithType: Iktan.Ecommerce.App.Interface
  fullName: Iktan.Ecommerce.App.Interface
  spec.csharp:
  - uid: Iktan
    name: Iktan
    href: Iktan.html
  - name: .
  - uid: Iktan.Ecommerce
    name: Ecommerce
    href: Iktan.Ecommerce.html
  - name: .
  - uid: Iktan.Ecommerce.App
    name: App
    href: Iktan.Ecommerce.App.html
  - name: .
  - uid: Iktan.Ecommerce.App.Interface
    name: Interface
    href: Iktan.Ecommerce.App.Interface.html
  spec.vb:
  - uid: Iktan
    name: Iktan
    href: Iktan.html
  - name: .
  - uid: Iktan.Ecommerce
    name: Ecommerce
    href: Iktan.Ecommerce.html
  - name: .
  - uid: Iktan.Ecommerce.App
    name: App
    href: Iktan.Ecommerce.App.html
  - name: .
  - uid: Iktan.Ecommerce.App.Interface
    name: Interface
    href: Iktan.Ecommerce.App.Interface.html
- uid: Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate*
  commentId: Overload:Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate
  href: Iktan.Ecommerce.App.Interface.IUserApplication.html#Iktan_Ecommerce_App_Interface_IUserApplication_Authenticate_System_String_System_String_
  name: Authenticate
  nameWithType: IUserApplication.Authenticate
  fullName: Iktan.Ecommerce.App.Interface.IUserApplication.Authenticate
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task{Iktan.Ecommerce.Transversal.Common.Response{Iktan.Ecommerce.App.DTO.UserDTO}}
  commentId: T:System.Threading.Tasks.Task{Iktan.Ecommerce.Transversal.Common.Response{Iktan.Ecommerce.App.DTO.UserDTO}}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<Response<UserDTO>>
  nameWithType: Task<Response<UserDTO>>
  fullName: System.Threading.Tasks.Task<Iktan.Ecommerce.Transversal.Common.Response<Iktan.Ecommerce.App.DTO.UserDTO>>
  nameWithType.vb: Task(Of Response(Of UserDTO))
  fullName.vb: System.Threading.Tasks.Task(Of Iktan.Ecommerce.Transversal.Common.Response(Of Iktan.Ecommerce.App.DTO.UserDTO))
  name.vb: Task(Of Response(Of UserDTO))
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Iktan.Ecommerce.Transversal.Common.Response`1
    name: Response
    href: Iktan.Ecommerce.Transversal.Common.Response-1.html
  - name: <
  - uid: Iktan.Ecommerce.App.DTO.UserDTO
    name: UserDTO
    href: Iktan.Ecommerce.App.DTO.UserDTO.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Iktan.Ecommerce.Transversal.Common.Response`1
    name: Response
    href: Iktan.Ecommerce.Transversal.Common.Response-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Iktan.Ecommerce.App.DTO.UserDTO
    name: UserDTO
    href: Iktan.Ecommerce.App.DTO.UserDTO.html
  - name: )
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
